### ISSUE TITLE
The `codicons` are looking weird

### ISSUE THREAD

**Issue by Alienover** [onsails/lspkind.nvim#27]
```
System: macOS 12.0.1
Terminal: Kitty, iTerm2
Font Family: VictorMono Nerd
```

### Description
No matter which terminal I was using (Kitty, iTerm2, or native terminal), and no matter which nerd font I was using, the `codicons` still didn't look good. Even when I copied the icons from github, they were still the same.

![image](https://user-images.githubusercontent.com/12182069/139612142-af3c35bc-cef9-4000-92b5-138a449ca04c.png)

**Comment by wookayin** [comment]
You need to use vscode's codicon.ttf (https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf)

FYI Nerd fonts do not include VSCode codicon symbols. When nerd fonts are used, you can use the `defult` preset.
