### ISSUE TITLE
Codicons used in screenshot

### ISSUE THREAD

**Issue by adsnaider** [onsails/lspkind.nvim#42]
Was wondering if it would be possible to have a list of the codicons you have in the README's screenshot alongside with the font necessary for them.

**Comment by ajitid** [comment]
The font can be grabbed from here https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf

Though setting  it `preset = 'codicons' gives a weird result.

![image](https://user-images.githubusercontent.com/26769888/153701073-ddc4c644-4ac6-4009-b2dc-198670d52dcd.png)

@onsails do we need to update in built preset mapping for it?

**Comment by ajitid** [comment]
Not repo author, but there are three steps:-
1. Download [codicon from here](https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf) and install it.
	- If on linux, check font name using `fc-list | grep -i codicon`. It would be codicon (notice it is not plural).
2. Setup lspkind

```lua
lua require('lspkind').init({ preset = 'codicons' })
```

If you are using nvim-cmp, an additional step is needed. Add this to `cmp.setup`

```lua
  formatting = {
    format = require'lspkind'.cmp_format({
      mode = 'symbol',
      maxwidth = 50,
    })
  }
```
3. Now the hard part. Your terminal emulator must be able to use codicon symbols as the fallback or it should give you an option to override few (unicode) chars with other font. Here's what looks like for kitty term:

https://github.com/ajitid/dotfiles/blob/2fb58488b07789b846a530c7edc79754bcea3fc2/kitty/.config/kitty/kitty.conf#L69

Once you make these changes, reopen your terminal, open nvim and then try checking if it works.
