### ISSUE TITLE
Error E5108: Error executing ...lspkind.lua:3: attempt to call field 'init' (a nil value)

### ISSUE THREAD

**Issue by zeitchef** [onsails/lspkind.nvim#45]
I'm getting the following error on startup since the last update:
![Screen Shot 2022-04-18 at 12 28 11](https://user-images.githubusercontent.com/6670659/163795925-ec1abbb8-788b-4ff1-a8a9-131158196948.jpg)

**Comment by thedawnboy** [comment]
I have the same problem

**Comment by hewenjin** [comment]
same for me

**Comment by charlesnicholson** [comment]
This hit me as well, when I upgraded to the new neovim 0.7 release.

**Comment by vuki656** [comment]
There was an [undocumented breaking change](https://github.com/onsails/lspkind.nvim/pull/44/commits/a505a3790f4b225e5a699c4420ba2e85357ae1cb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23) in #44.

Just change `init` to `setup` like so:

```lua
local lspkind = require("lspkind")

lspkind.setup()
```

**Comment by vuki656** [comment]
Also, note that the plugin changed it's name from `lspkind-nvim` to `lspkind.nvim`

**Comment by charlesnicholson** [comment]
Rewriting my init code in the style of the updated homepage fixed it all; thanks for the pointer!

**Comment by zeitchef** [comment]
Would still be nice for a little warning.

**Comment by thedawnboy** [comment]
Thanks, works well

**Comment by wookayin** [comment]
It's a shame that a PR #44 breaks the plugin without any warning, deprecation, or documentation.

`lspkind.presets` and `lspkind.symbol_map` are gone and removed, often used in completion engines: use `lspkind.get_symbol(kind)` instead.
