### ISSUE TITLE
Show icons first then menu item second

### ISSUE THREAD

**Issue by eskinderg** [onsails/lspkind.nvim#51]
I was using lspkind with nvim-cmp and it is working fine.
One thing i would like to have as an option is that, is there a way to make the icons appear first and then the menu item second ?

![Screenshot from 2022-08-06 13-59-18](https://user-images.githubusercontent.com/5959962/183246186-ddacfe7c-b907-4c92-ba04-de066fab1981.png)

Show Icons First then menu item second
![Screenshot from 2022-08-06 13-59-46](https://user-images.githubusercontent.com/5959962/183246204-c220862a-21c6-44e3-a9a2-ae1c6c25164f.png)

**Comment by mario-amazing** [comment]
You can check cmp Wiki:
https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#basic-customisations
Hope it'll help

**Comment by eskinderg** [comment]
@mario-amazing Thanks that is exactly what i was looking for
