### ISSUE TITLE
Text type suggestion is off to the left by one.

### ISSUE THREAD

**Issue by YongzeYao** [onsails/lspkind.nvim#59]
![image](https://user-images.githubusercontent.com/22460339/209996285-0d850074-4e39-4496-a4a3-55ba712a9bab.png)
Here is how it looks like.
I want all kinds to align perfectly. Is this a bug or is it because I have a messed up config.
Here is my nvim-cmp config:
```lua
	formatting = {
		format = lspkind.cmp_format({
			maxwidth = 50,
			ellipsis_char = "...",
		}),
	},
```

**Comment by onsails** [comment]
I believe it has nothing to do with lspkind because it only works with "f Function" row, not the function completion.
Does this problem persist if you disable lspkind?

**Comment by YongzeYao** [comment]
Huh... Interesting, same behavior even if I turned off lspkind. 
I will look into this and see if there is something wrong with my nvim-cmp.
Thank you! And happy new year! : )
