### ISSUE TITLE
Brown icons

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [onsails/lspkind.nvim#60]
Use dracula vim theme. Check out my dots repo to reproduce issue. These is how it's look like https://imgur.com/a/zyBBjy5

**Comment by Bogdan-Torkhov** [comment]
@onsails Where are you???

**Comment by grimerssy** [comment]
Consider looking through highlight groups of your colorscheme. This plugin has nothing to do with icon colors

**Comment by onsails** [comment]
Icons is just font symbols, tuning your hl group is the way.
