### ISSUE TITLE
How to get source visible in the cmp menu?

### ISSUE THREAD

**Issue by s1n7ax** [onsails/lspkind.nvim#61]
I have passed following configuration to cmp. It shows the kind icons and text but not the source. What do I have to do to get the source shown in the menu similar to screenshot in the README.md such as `[LSP]`

```lua
formatting = {
        format = lspkind.cmp_format({
                mode = 'symbol_text',
                with_text = true,
                maxwidth = 50,
        }),
},
```

**Comment by lyonelz96** [comment]
Hey! I ran into the same problem haha but with a little bit of digging found this: https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#basic-customisations
