### ISSUE TITLE
lsp-kind icons not working with nerd font.

### ISSUE THREAD

**Issue by fnacarellidev** [onsails/lspkind.nvim#69]
I'm using lspkind (latest) and i'm using JetBrains Nerd Font, suddenly the icons that show on nvim-cmp stopped working, some icons work, some don't.

Here's what i'm getting:

![image](https://github.com/onsails/lspkind.nvim/assets/97247063/a65278ee-38d2-435d-90c8-1b3792cd2385)

**Comment by ciza99** [comment]
I have the same issue, other nerd font icons work just fine

**Comment by egeesin** [comment]
> edit: I have uninstalled the nerd font I was using, downloaded one from their website, and installed it and it resolved the issue. Although I chose to go with a different font so I am not sure what the problem was...

Old versions of Nerd Fonts didn't have Codicon (VSCode) icon set, maybe that's why? It might be worth to note that in the README if that's the case.

**Comment by m010-cpu** [comment]
@egeesin @ciza99 @fnacarellidev 
I had the same issue but finally solved it. They removed `mdi` icons from all the nerd fonts since 3.0.0 , so you have to replace all the `mdi` icons from your config files.

<img width="1087" alt="Screenshot 2023-07-19 at 15 03 56" src="https://github.com/onsails/lspkind.nvim/assets/81363508/6db85a78-93ca-4a52-a13b-3b80e9532e86">

Hopefully, this guy made a life saver script that can check and fix removed icons from nerd fonts and make perfect replacement proposition:

https://github.com/loichyan/nerdfix

Here is the new valid lspkind setup after fix:
```lua
lspkind.init({
  -- enables text annotations
  --
  -- default: true
  mode = 'symbol_text',

  -- default symbol map
  -- can be either 'default' (requires nerd-fonts font) or
  -- 'codicons' for codicon preset (requires vscode-codicons font)
  --
  -- default: 'default'
  preset = 'codicons',

  -- override preset symbols
  --
  -- default: {}
  symbol_map = {
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = ""
  },
})
```

**Comment by fnacarellidev** [comment]
Some of the symbols still doesn't work, I also tried setting up the codicons by my own but the icons were way too small.

The 'text' symbol for example did not work for me

**Comment by m010-cpu** [comment]
> Some of the symbols still doesn't work, I also tried setting up the codicons by my own but the icons were way too small.
> 
> The 'text' symbol for example did not work for me

Do you have any contact info or discord tag, maybe I can try help you fix that (without spamming here) ?

**Comment by fnacarellidev** [comment]
Sure, hit me up, my discord user is _fabin_

**Comment by fnacarellidev** [comment]
If anyone else is experiencing this problem, it was solved by running `fc-cache -fv` and by setting the icons manually as @m010-cpu mentioned.
