### ISSUE TITLE
Autocomplete options cannot be selected via TAB or ENTER

### ISSUE THREAD

**Issue by kelphil** [onsails/lspkind.nvim#77]
Autocomplete options cannot be selected via TAB or ENTER shown below.

![image](https://github.com/onsails/lspkind.nvim/assets/16230838/ba8ec0fd-10af-4d86-a66c-1fc69f7fe421)

Here is my cmp.setup mapping:

![image](https://github.com/onsails/lspkind.nvim/assets/16230838/f1ba4659-4086-4e07-a9b8-0423bcfdfa82)

**Comment by onsails** [comment]
lspkind doesn't deal with bindings, it just adds icons to completion items. Please refer to cmp documentation or community discussions.
