### ISSUE TITLE
Some color emojis don't work

### ISSUE THREAD

**Issue by rickalex21** [onsails/lspkind.nvim#78]
Hello,

I think this may be more of a neovim/vim specific question but I wanted to point out that
some emojis are not showing up. I know it's not my terminal/font because I can easily
paste the symbols in there but inside neovim I can't see the scissors emoji for some
reason. I can see the key though.

🔑
✂️

Not sure if this is related to [kitty issue 2500](https://github.com/kovidgoyal/kitty/issues/2500).

If anyone has any input I would appreciate it. 

Thanks

**Comment by onsails** [comment]
Irrelated to this plugin, it's either terminal/font or your neovim configuration problem.
